name: Python CICD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Run mypy
      run: |
        mypy $(git ls-files '*.py')

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test_bank.py --doctest-modules --junitxml=test-results/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Publish test results
      uses: aiaibot/publish-unit-test-result@v1
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: test-results/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false